name: Build and push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/docling-inference

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build image
        run: docker build --tag $IMAGE_ID:latest --label "runnumber=${GITHUB_RUN_ID}" .
      - name: Push image
        run: |
          docker push $IMAGE_ID:latest
